title: Dante Gaxiola
email: dantemacabeo@gmail.com
instagram_username: dantegaxiola
pinterest_username: dantegaxiola
description: Memorización Deliberada, Escritura Fluída, Capoeira, y más.

baseurl: ""
url: ""
theme: minima
plugins:
  - jekyll-feed

minima:
  skin: dark
