title: Dante Gaxiola
email: dantemacabeo@gmail.com
instagram_username: dantegaxiola
pinterest_username: dantegaxiola
description: Memorización Deliberada, Escritura Fluída, Capoeira, y más.

baseurl: ""
url: ""

remote_theme: jekyll/minima
minima:
  skin: dark

plugins:
  - jekyll-feed

