---
layout:     post
title:      Desafíos
date:       Sun Apr 24 18:34:06
---

El proceso general de aprendizaje es un proceso complejo al que generalmente se le entiende poco, por más que todos tengamos experiencia con él, tanto formal como informalmente. Esta falta de comprensión puede volverlo un proceso mucho más difícil y desafiante en su dimensión emocional de lo que necesita ser. Lamentablemente, no es común un acompañamiento efectivo ni una cultura que ayude a enfrentar los desafíos que trae consigo, por más que sea un proceso tan fundamental y potencialmente satisfactorio. En este artículo realizaré una propuesta de modelo de dicho proceso, de sus fases más comunes y de los desafíos que traen consigo, así como las crisis que comúnmente pueden desatar.

Aunque esta propuesta puede tener aplicaciones para la adquisición de conocimiento, está centrada más bien en el desarrollo de habilidades y en el nivel en el desempeño en la realización de una actividad. Iniciemos, como lo hemos hecho en otros lugares, entendiendo el aprendizaje como un proceso de adquisición de representaciones mentales y habilidades, así como la capacidad de acceder a ellos para comprender y enfrentar problemas futuros. De acuerdo con ello, toda adquisición de habilidades requiere el desarrollo de cierto nivel de conocimiento, tanto de las técnicas como del uso de herramientas necesarias para un buen desempeño.

El camino del aprendizaje, entonces, puede entenderse, en cuanto proceso general, como su desarrollo a través del tiempo. Una idea común, pero muy poco cercana al proceso real, lo imagina como un proceso lineal y ascendente, en el que se van adquiriendo los conocimientos y habilidades de manera paulatina pero constante. En realidad, este proceso sigue una serie de fases más o menos regulares, aunque de duración variable, a las que, por ello mismo, se les puede comprender y uno puede prepararse para hacerles frente. Se trata de un proceso cíclico con momentos de avance y retroceso en el desempeño que ofrecen oportunidades y desafíos específicos propios de cada fase o momento.

De lo que podemos estar seguros es de que este proceso requiere desarrollar habilidades y herramientas que se adecúen al desafío que presenta la complejidad creciente del material o tipo de trabajo que se va desarrollando y, a menudo, la transformación de la totalidad de nuestra forma de práctica o trabajo. Esta necesidad es común a todo aprendizaje prolongado, aunque pueda resultar difícil de reconocer, en buena medida por el desconocimiento de las fases y dinámicas comunes del proceso, así como por la creencia extendida de que basta con practicar mucho y esforzadamente para aprender (algo así como "la práctica hace al maestro"). El mayor riesgo que implica fallar en esta previsión o consciencia del proceso es la posibilidad de crisis emocionales e incluso personales, especialmente si partimos de lo que la Dra. Carol Dweck, investigadora de la psicología del desarrollo, denomina una "mentalidad fija"[1], la creencia en que nuestras capacidades o nuestro potencial son innatos o fijos y reflejan nuestras características o valor esenciales.

Fases del proceso de aprendizaje
--------------------------------

Como decimos, el proceso de aprendizaje sigue, regularmente, distintas fases que se repiten cíclicamente con niveles crecientes de complejidad. Estas fases no tienen una duración determinada ni es fácil identificar cuando inician o terminan, pero tienen características suficientemente distintivas y son tan recurrentes que vale mucho la pena tenerlas en mente. Veámoslas brevemente para darnos una idea general del proceso.

### Desarrollo inicial del proceso de aprendizaje

Cuando comenzamos un nuevo proceso de aprendizaje, en un área con la que no estamos familiarizados, pasamos por una fase de desarrollo inicial. Cuando el proceso está bien organizado, aprendemos las herramientas y técnicas más básicas con las que podemos realizar la actividad. Por ejemplo, al aprender un nuevo idioma, aprenderemos las palabras y expresiones más comunes, suficientes para mantener una conversación muy elemental. Al aprender un juego, aprenderemos las reglas y movimientos básicos del mismo, que nos permitan realizarlo en un nivel muy elemental. Este momento del proceso puede generar una confianza poco informada sobre la velocidad en la que aprenderemos y crear expectativas poco razonables, que se verán cuestionadas tan pronto como la complejidad de la actividad vaya creciendo.

### Fase de adaptación

Sea que estamos iniciando el proceso de aprendizaje o que, en un momento más adelantado del proceso, hayamos decidido explorar un estilo o sistema de trabajo nuevo, es inevitable que, al intentar utilizar técnicas o herramientas más sofisticadas, nuestro desempeño disminuya temporalmente. Este momento puede ser entendido como una fase de adaptación en la que es común que ocurra lo que a veces se conoce como "parálisis por análisis", la dificultad o incapacidad de tomar decisiones por un exceso de pensamientos reflexivos y por el cuestionamiento de las herramientas en las que antes podíamos confiar junto con la falta de dominio de las que estamos intentando integrar. Regresando al aprendizaje de un idioma extranjero, cuando comenzamos a ver distintos tiempos verbales, reglas gramaticales o al aumentar nuestro vocabulario, es común que aún las conversaciones que antes podíamos mantener con cierta facilidad ahora se vuelvan extremadamente difíciles. Si ponemos como ejemplo al ajedrez, esto puede ocurrir al comenzar a pensar en el "valor" de las piezas, en estrategias de apertura o en el desarrollo táctico del juego. Se trata de uno de los momentos más vulnerables del proceso de aprendizaje y también uno de los que más fácilmente provocan crisis en quienes lo atraviesan. Sin embargo, es un proceso absolutamente necesario para aprender algo nuevo o para ir más allá del nivel en el que nos encontramos. Josh Waitzkin, maestro del ajedrez y del taichí así como un profundo pensador del aprendizaje, le llama a la disposición a aprender algo nuevo o probar un estilo o sistema nuevo "invertir en perder" y utiliza la metáfora del cangrejo ermitaño para pensar la fase de adaptación. Así como el cangrejo llega a un punto en el que no le es posible crecer más dentro del caparazón que hay estado llevando y requiere dejarlo para poder entrar en uno nuevo, pasando por un periodo de enorme vulnerabilidad.[2]

### Meseta de incorporación

Después del periodo inicial de adaptación, lo más común es pasar por un periodo o fase de incorporación paulatina (una especie de "meseta") en la que el aprendizaje es bastante lento, pero al menos hemos recuperado cierta estabilidad al desarrollar nuestra actividad. Al aprender un idioma, tal vez nos falte mucho para dominar los tiempos o reglas más difíciles, pero podemos tener una conversación básica y poco a poco entender y utilizar construcciones cada vez más complejas. En el ajedrez, aunque aún estemos lejos de dominar las aperturas o para valorar velozmente las distintas piezas, al menos podemos evitar errores importantes y comenzamos a desarrollar una comprensión general del juego más profunda. El avance paulatino de esta fase puede hacer que se confunda con una fase de estancamiento, pero se distingue de esta última en que es comúnmente seguida por una fase de desarrollo acelerado.

### Desarrollo acelerado

Le llamo fase de desarrollo acelerado al proceso en que la incorporación paulatina de nuevas técnicas y herramientas da paso a una incorporación acelerada y a menudo súbita. Generalmente es el resultado de la práctica deliberada o intencional, pero por su naturaleza tiene semejanzas con lo que Mihály Csikszentmihalyi ha denominado "estado de *flow*". [3] Las distintas técnicas y habilidades comienzan a comprenderse con mayor profundidad y a realizarse de una manera más automática, permitiéndonos concentrarnos en la tarea a la mano con mayor facilidad. Es como si tomaran o mostraran un nuevo sentido y ocurrieran con mucha fluidez. Tal vez una analogía apropiada para ilustrarlo ocurre cuando estamos armando un rompecabezas y, después de un tiempo de avance lento y de gran dificultad, comenzamos a ver la imagen formarse y cada pieza se puede ubicar con mayor facilidad. Sin duda se trata de una fase sumamente satisfactoria, pero que tampoco está libre de desafíos.

### Estancamiento

La última fase de este proceso general de aprendizaje en la fase de estancamiento. Ocurre cuando hemos dominado al menos relativamente un conjunto de técnicas, herramientas y estrategias generales y se refiere al periodo en el que disminuye considerablemente la velocidad de aprendizaje. También puede ser el resultado de dejar de realizar una práctica efectiva y de repetir mecánicamente los mismos procedimientos sin esforzarnos por mejorar en ellos. En realidad, dependiendo de nuestros objetivos, no se trata necesariamente de algo negativo. Por ejemplo, si nuestro objetivo es utilizar la bicicleta como medio de transporte, tal vez estemos satisfechos con alcanzar un nivel suficiente de habilidad que nos permita realizar la actividad sin mucho esfuerzo y sin pensar demasiado en ella. En cambio, si las demandas externas superan nuestra capacidad o nuestro objetivo es el de continuar nuestro aprendizaje y desarrollar la maestría en una actividad determinada, el estancamiento es una señal importante de que necesitamos modificar nuestras estrategias y herramientas generales. Al hacerlo, lo común es que el proceso de paso a nuevos periodos de adaptación, mesetas y, con algo de suerte, de desarrollo acelerado.

Crisis en el proceso de aprendizaje
-----------------------------------

El proceso general de aprendizaje, como hemos visto, transcurre en una serie de fases o momentos previsibles, pero que traen consigo desafíos y riesgos específicos a cada uno de ellos. De manera general, el mayor riesgo es que los momentos de tránsito se transformen en crisis, no sólo técnicas o inherentes al proceso, sino crisis emocionales que pueden desarrollarse incluso en crisis personales o de la imagen que tenemos de nosotros mismos y nuestras capacidades. Una crisis, en este sentido, se refiere a un momento o periodo de insatisfacción y desesperación. Pueden ser el resultado de la comparación entre nuestras expectativas y nuestro desempeño efectivo, o entre las demandas de nuestra actividad (especialmente cuando tienen implicaciones profesionales o académicas) y nuestra capacidad en un momento dado.

Debido a que no anticipamos las dificultades y desafíos propios del proceso, ni nos preparamos para examinar habitualmente nuestras herramientas generales, es común que, al enfrentarnos a sus limitaciones, sintamos desesperación. Esta última se exacerba cuando no logramos distinguir entre nuestra capacidad básica de aprendizaje y las habilidades y herramientas con las que contamos en un momento dado. Al hacerlo, perdemos confianza en esa capacidad, lo que puede traer consecuencias importantes para nuestra autoimagen e incluso nuestro sentido de dignidad, produciendo lo que se conoce comúnmente como "síndrome del impostor": una gran dificultad por reconocer nuestros logros y una sobreidentificación con nuestras limitaciones y fallos. Afortunadamente, esto no es algo necesario. Antes de retomar este punto, veamos las características de las crisis más comunes que acompañan las distintas fases del proceso general de aprendizaje.

### Crisis de la fase de adaptación

La primera crisis común ocurre al entrar en la fase de adaptación, sea del proceso de aprendizaje general de una nueva área o al probar con herramientas y técnicas nuevas. Como hemos dicho, es esperable que ocurra una desestabilización y un retroceso en el desempeño, a menudo provocado por una parálisis por análisis. El problema ocurre cuando lo interpretamos como señal de que hay un problema, sea con nuestra propia capacidad o con la efectividad de las técnicas que estamos explorando, antes de haberles dado una oportunidad adecuada. Esto no sólo provoca una reacción emocional de resistencia innecesaria, obstaculizando el proceso, sino que puede hacer que se abandone por completo el proyecto o que se regrese a las herramientas y estrategias anteriores, con las que tenemos más familiaridad. Naturalmente, es posible que el nuevo método de trabajo no sea efectivo para nosotros, y es importante estar abiertos a esa posibilidad, pero no podremos saberlo si no le damos el tiempo y el esfuerzo necesarios para probarlos. Una oportunidad justa, podríamos decir.

### Crisis en la meseta de incorporación

Aun cuando logremos pasar el retroceso momentáneo que implica la fase de adaptación, el trabajo necesario para incorporar profundamente los nuevos principios y estrategias puede ser mayor al que anticipamos. También aquí existe el riesgo de regresar a técnicas anteriores, menos efectivas pero con las que tenemos más familiaridad. Es muy importante cultivar la persistencia y la confianza en esta fase del proceso, y tratar de disfrutar y celebrar los pequeños logros que vayamos consiguiendo. La recompensa, con algo de suerte, será la fase de desarrollo acelerado.

### Crisis de estancamiento

Cuando logramos incorporar el nuevo método de trabajo, el avance en nuestras capacidades necesariamente reducirá su velocidad, dando pie a la fase de estancamiento. Como hemos, dicho, no se trata necesariamente de algo negativo, pero si el desarrollo acelerado produce una confianza excesiva en nuestro progreso, también puede dar paso a una crisis. En este momento, es importante reflexionar sobre nuestros objetivos, deseos y también sobre las demandas de nuestra actividad, en caso de que las hubiere, y tal vez necesitemos ajustar nuestras expectativas. En cualquier caso, considero que es muy importante dar espacio para la celebración y el aprecio de nuestro avance y aprendizaje hasta este momento. Si nuestros objetivos o las demandas externas se mantienen alejados de nuestro nivel real de desempeño por mucho tiempo, entonces es necesario buscar nuevas estrategias, herramientas, ejercicios, etc., que nos permitan superar el estancamiento, y lo mejor es hacerlo con la consciencia de las posibles fases siguientes.

Es importante recordar que las crisis e incluso el síndrome del impostor pueden ser señales positivas en el proceso de aprendizaje. Pueden indicar cualidades positivas, como la realización de una práctica reflexiva sobre nuestras herramientas y habilidades. Algunos estudios muestran una relación positiva entre los "pensamientos de impostor" y el desempeño laboral[4], y es posible reconocer que a menudo son los estudiantes con mejores resultados los que más batallan con su proceso, especialmente cuando se sienten estancados en un nivel particular. Esto último puede deberse, seguramente, a que es necesario cierto nivel de capacidad para reconocer las limitaciones de nuestros acercamientos y para buscar mejores alternativas.

Lo más importante aquí es recordar que es posible anticipar o evitar las crisis en el proceso de aprendizaje, integrarlas activamente y construir una confianza cada vez más informada en nuestras capacidades. Espero que esta forma de entender el proceso de aprendizaje sea una herramienta útil para quienes se encuentran en cualquiera de sus fases y enfrentando sus diversos desafíos. Especialmente si estás comenzando un nuevo proceso, sea iniciando en una nueva disciplina o área de aprendizaje, o sea porque estás explorando nuevas técnicas, métodos o un sistema diferente al que estás acostumbrado, mantener la consciencia de las fases, desafíos y crisis posibles puede ser una gran ventaja.

Notas

[1] Cfr. Dweck, Carol S., "Capítulo 1. Las mentalidades", en *Mindset. La actitud del éxito*, Editorial Sirio, 2016 [2006].

[2] Cfr. Waitzkin, Josh, *El arte de aprender*,

[3] Cfr. Csikszentmihalyi, Mihály, *Fluir (Flow). Una psicología de la felicidad*, Editorial Kairós, España, 1996. El estado de *flow* es un estado de intenso involucramiento en una actividad, altamente satisfactorio, en el que nos desempeñamos en un nivel mayor al usual y generalmente con un menor esfuerzo consciente.

[4] Cfr. Tewifik, Basima, "The Unexpected Benefits of Doubting Your Own Competence", recuperado de http://ideas.wharton.upenn.edu/research/imposter-syndrome-unexpected-benefits/ el 11 de mayo de 2022.
